### ISSUE TITLE
Pi Zero W Compatibility

### ISSUE THREAD

**Issue by MiklZh** [nebrius/raspi-io#89] opened 2017-04-11 13:28 UTC
As the Pi Zero W has a different hardware revision to the Zero, running raspi-io fails.

9000c1 is the new rev.

**Comment by nebrius** [comment] 2017-04-11 18:11
Thanks for the rev number @MiklZh! My Pi Zero W just shipped, so once it arrives I can test the fix and have it updated.

Can you post the exact error you get? Raspi IO _should_ degrade gracefully when it doesn't recognize the board revision.

**Comment by MiklZh** [comment] 2017-04-11 18:42
I get this message: Unknown board revision ${rev}, assuming Raspberry Pi 3 pinout.
I tried add in raspi-board file rev number "9000c1" with every board VERSION, but johnny-five example don't starting (no error and led not blink)

**Comment by nebrius** [comment] 2017-04-11 19:48
> I get this message: Unknown board revision ${rev}, assuming Raspberry Pi 3 pinout.
I tried add in raspi-board file rev number "9000c1" with every board VERSION, but johnny-five example don't starting (no error and led not blink)

The message you received is just a warning, not an error, and in the case of the Pi Zero shouldn't cause any issues.

Can you post the code you ran?

**Comment by MiklZh** [comment] 2017-04-11 20:05
> Can you post the code you ran?

```
var five = require("johnny-five");
var Raspi = require("raspi-io");
var board = new five.Board({
  io: new Raspi()
});

board.on("ready", function() {
  var led = new five.Led("P1-13");
  led.blink();
});
```

Output:
```pi@raspberrypi:~ $ sudo node t3.js
Unknown board revision 9000c1, assuming Raspberry Pi 3 pinout.
1491940679238 Device(s) RaspberryPi-IO
1491940679372 Connected RaspberryPi-IO
1491940679427 Repl Initialized
>>
(To exit, press ^C again or type .exit)
>>
1491940709437 Board Closing.
```

**Comment by nebrius** [comment] 2017-04-11 20:13
The code looks correct. Are you sure that your LED is inserted in the correct direction and is attached to the correct pin? Installing them backwards will cause them to not work.

**Comment by MiklZh** [comment] 2017-04-11 20:19
1. I try this code on Raspberry Pi 3 and LED blink.
2. I try node-rpio library and LED blink on Raspberry Zero W.

**Comment by nebrius** [comment] 2017-04-11 20:21
🤔. Ok, I'll see if I can reproduce this once my own Zero W comes, I'm not sure why it isn't working at this point.

**Comment by my-wheel** [comment] 2017-04-14 16:17
I can confirm the issue raised by MiklZh. I get message:
"Unknown board revision 9000c1, assuming Raspberry Pi 3 pinout."
and no Led is blinking.

**Comment by nebrius** [comment] 2017-04-20 02:25
I received my Raspberry Pi Zero W in the mail, and I have _some_ results. It turns out that "Unknown board revision 9000c1, assuming Raspberry Pi 3 pinout." is _completely_ unrelated to LEDs not working, as I suspected. The graceful degradation worked in the only part of the codebase that is board version aware, as it turns out

I just published a new version of raspi-board, the module that is responsible for determining which version of the RPi you're running on and setting the pin aliases up, so you won't get that error message anymore.

Now for the bad news.

It still doesn't work, even with this fix, and I have _absolutely no idea why_. I've traced the code through and all C++ calls are being called correctly, and there are no errors from Wiring Pi. I'll keep digging, but at this point in time I'm stumped 😕 .

**Comment by nebrius** [comment] 2017-04-26 03:03
Raspi IO 8.0.0 is out! This version switches from using Wiring Pi to pigpio under the hood and gets around the broken GPIO issue, and also includes all the fixes to not break bluetooth on the RPi W Zero.

Let me know if this fixes it for you!

**Comment by nebrius** [comment] 2017-06-02 22:21
Closing as this has been fixed. Feel free to reopen if there's still some issues.

**Closed by nebrius** 2017-06-02 22:21 UTC
